import json,sqlite3,shutil,subprocess
from pathlib import Path
from tools.findings_tracker import add_finding
from tools.entity_resolution import resolve_or_create_entity
w=Path('/tmp/osint-disclosures-C2sHVOQq');dest=Path('investigations/hassan-boston/evidence/disclosures');dest.mkdir(parents=True,exist_ok=True)
# Archive raw successful query artifacts and original public PDF, retaining query provenance.
for p in w.iterdir():
 if p.suffix in ('.json','.pdf','.txt','.png','.py') and p.is_file():shutil.copy2(p,dest/p.name)
ids={}
u='http://docquery.fec.gov/cgi-bin/fecimg/?93020012770'
f=add_finding(target_name='Hicham Ali Hassan',summary='FEC record dated November 6, 1992 lists Hicham Ali Hassan of Hull with employer Tannery and a $500 contribution',finding_type='background',detail='The official FEC Schedule A API returns contributor_name HASSAN, HICHAM ALI; contributor_city HULL; contributor_state MA; contributor_employer TANNERY; receipt date 1992-11-06; amount 500.0; committee C00174862 (Committee to Re-Elect Senator Edward M Kennedy); sub_id 3061920110003101283; image 93020012770. Exact multi-part name plus the Tannery business affiliation support identity resolution. Later employer-matched rows run through 1998. Raw results contain multiple rows sharing date, amount and image; no aggregate donation total is asserted. The record establishes a reported employer/business link and political contribution, not source of wealth or influence. Durable API record: investigations/hassan-boston/evidence/disclosures/fec-hicham-1.json.',evidence_ids=[u],source_datasets=['fec'],confidence='high',date_of_event='1992-11-06',lead_id=95679,claim_type='paraphrase',source_quotes={u:{'quote':'"contributor_name": "HASSAN, HICHAM ALI"; "contributor_city": "HULL"; "contributor_employer": "TANNERY"; "contribution_receipt_date": "1992-11-06"; "contribution_receipt_amount": 500.0','page':'FEC Schedule A API row sub_id 3061920110003101283','assessment':'Official API fields; original image link preserved. Not a claim that older duplicate entries are separate donations.'}},profile_id='hassan-boston');ids['hicham_fec']=f
u='https://api.ocpf.us/report/pdf/841345'
f=add_finding(target_name='Houssam Ali Hassan',summary='July 2022 Massachusetts campaign report identifies Houssam Hassan as Developer/Owner at Silverstone Development',finding_type='background',detail='OCPF Composite Depository Bank Report for Campbell, Andrea Joy (CPF ID 15931), reporting period 2022-07-01 to 2022-07-31, filed 2022-08-02, lists Hassan, Houssam as an individual donor, Developer/Owner, Silverstone Development, a $300 credit-card receipt dated 2022-07-18. Source PDF page 23; city continues on page 24. The source business address matches the official Massachusetts PEMBROKE TOWNHOUSE LLC (001037265) record identifying HOUSSAM ALI HASSAN as resident agent and manager; this provides a second contextual identifier. Corporate evidence maintained by Track B at evidence/corporate/entity-001037265.txt. Source occupation/employer fields are reported declarations, not independent proof of equity ownership. Address is retained in original evidence for disambiguation and omitted from public-facing summary. Durable PDF and visually reviewed page: evidence/disclosures/ocpf-841345.pdf and ocpf-page-23.png.',evidence_ids=[u],source_datasets=['official_website'],confidence='high',date_of_event='2022-07-18',lead_id=95682,claim_type='paraphrase',source_quotes={u:{'quote':'7/18/2022 Hassan, Houssam Individual Developer/Owner $300.00\nCredit Card ... Silverstone Development','page':'23 (city continuation p24); report identification p1','assessment':'Original PDF downloaded from Massachusetts OCPF; page 23 visually reviewed; name and contextual corporate address match support attribution.'}},profile_id='hassan-boston');ids['houssam_ocpf']=f
# Conservative entity rows: reported business labels only, without inventing legal suffixes.
db=sqlite3.connect('investigation.db');db.row_factory=sqlite3.Row
for name,typ,notes in [('The Tannery','company','Retail business label; FEC employer field TANNERY/THE TANNERY. Legal vehicle resolution belongs to corporate track.'),('Silverstone Development','company','Employer/business label reported for Houssam Hassan in OCPF report 841345. Legal vehicle and equity ownership unresolved.')]:
 r=resolve_or_create_entity(db,name,entity_type=typ,source='hassan-boston disclosures primary records',notes=notes);ids[name+'_entity']=r.entity_id
for fn,en in [('hicham_fec','The Tannery_entity'),('houssam_ocpf','Silverstone Development_entity')]:
 db.execute('INSERT OR IGNORE INTO finding_entities (finding_id,entity_id) VALUES (?,?)',(ids[fn],ids[en]))
db.commit();db.close()
leads=[['--title','Identify the legal vehicle and ownership behind Houssam Hassan’s Silverstone Development disclosure','--description','Official OCPF report 841345 identifies Houssam Hassan as Developer/Owner, Silverstone Development in July 2022. Name and business address match HOUSSAM ALI HASSAN in MA PEMBROKE TOWNHOUSE LLC 001037265. Resolve whether Silverstone Development is a legal entity or trade name, trace filings and financial/property vehicles, and determine documented role/ownership without treating self-reported Owner as title proof.','--category','entity','--priority','medium','--source','official_website','--target','Houssam Ali Hassan','--evidence','https://api.ocpf.us/report/pdf/841345','--related','95682','95688','--recommended-skill','trace-entity'],['--title','Verify Zappos investment terms and recipient vehicle for Concepts in 2018','--description','2018 published reporting quotes Tarek Hassan, CEO of Concepts International, confirming a Zappos relationship and reports investment. Obtain attributable company announcement or transaction documents; identify legal recipient, date, investment amount, equity percentage, restrictions and whether any proceeds reached property vehicles. Existing evidence supports a lead only: no terms or link to property capital yet. Exact SEC phrase Concepts International returns many unrelated issuers, so identify the legal vehicle before broad filing review.','--category','financial','--priority','high','--source','hypebeast','--target','Tarek Ali Hassan','--evidence','https://hypebeast.com/2018/8/concepts-amazon-zappos-partnership-investment-streetwear-industry','--related','95684','95686','--recommended-skill','analyze-filing']]
for i,args in enumerate(leads):
 pr=subprocess.run(['uv','run','python','tools/lead_tracker.py','add',*args,'--profile','hassan-boston'],capture_output=True,text=True);ids['lead_'+str(i)]=pr.stdout.strip();print(pr.stdout,pr.stderr)
(w/'persisted-ids.json').write_text(json.dumps(ids,indent=2));(dest/'persisted-ids.json').write_text(json.dumps(ids,indent=2));print(json.dumps(ids,indent=2))
