"""Local SQLite/FTS5 index for the public MuckRock API v2 corpus.

The index deliberately keeps MuckRock request metadata, communication bodies,
and file metadata separate.  Communication ``files`` references provide the
join from a released file back to its request.  A blank file ``doc_id`` is
treated as *DocumentCloud-unlinked* rather than proof that no duplicate exists
elsewhere in DocumentCloud.
"""

from __future__ import annotations

import json
import re
import sqlite3
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Iterable


DEFAULT_INDEX_DB = Path("datasets/muckrock_index.db")
PAGE_SIZE = 100
COLLECTIONS = (
    "requests",
    "communications",
    "files",
    "agencies",
    "jurisdictions",
)
COLLECTION_ORDERING = {
    "requests": "datetime_submitted",
    "communications": "datetime",
    "files": "datetime",
    "agencies": "name",
    "jurisdictions": "name",
}


SCHEMA = """
CREATE TABLE IF NOT EXISTS requests (
    id                  INTEGER PRIMARY KEY,
    title               TEXT NOT NULL DEFAULT '',
    requested_docs      TEXT NOT NULL DEFAULT '',
    slug                TEXT NOT NULL DEFAULT '',
    status              TEXT NOT NULL DEFAULT '',
    agency_id           INTEGER,
    user_id             INTEGER,
    embargo_status      TEXT NOT NULL DEFAULT '',
    datetime_submitted  TEXT NOT NULL DEFAULT '',
    datetime_updated    TEXT NOT NULL DEFAULT '',
    datetime_done       TEXT NOT NULL DEFAULT '',
    tracking_id         TEXT NOT NULL DEFAULT '',
    price               TEXT NOT NULL DEFAULT '',
    tags_json           TEXT NOT NULL DEFAULT '[]',
    indexed_at          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_muckrock_requests_agency
    ON requests(agency_id);
CREATE INDEX IF NOT EXISTS idx_muckrock_requests_status
    ON requests(status);
CREATE INDEX IF NOT EXISTS idx_muckrock_requests_updated
    ON requests(datetime_updated);

CREATE TABLE IF NOT EXISTS communications (
    id                  INTEGER PRIMARY KEY,
    request_id          INTEGER,
    from_user_id        INTEGER,
    to_user_id          INTEGER,
    subject             TEXT NOT NULL DEFAULT '',
    datetime            TEXT NOT NULL DEFAULT '',
    response            INTEGER NOT NULL DEFAULT 0,
    autogenerated       INTEGER NOT NULL DEFAULT 0,
    communication_body  TEXT NOT NULL DEFAULT '',
    status              TEXT NOT NULL DEFAULT '',
    indexed_at          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_muckrock_communications_request
    ON communications(request_id);
CREATE INDEX IF NOT EXISTS idx_muckrock_communications_response
    ON communications(response);
CREATE INDEX IF NOT EXISTS idx_muckrock_communications_datetime
    ON communications(datetime);

CREATE TABLE IF NOT EXISTS files (
    id                  INTEGER PRIMARY KEY,
    url                 TEXT NOT NULL DEFAULT '',
    datetime            TEXT NOT NULL DEFAULT '',
    title               TEXT NOT NULL DEFAULT '',
    source              TEXT NOT NULL DEFAULT '',
    description         TEXT NOT NULL DEFAULT '',
    doc_id              TEXT,
    pages               INTEGER,
    indexed_at          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_muckrock_files_doc_id
    ON files(doc_id);
CREATE INDEX IF NOT EXISTS idx_muckrock_files_datetime
    ON files(datetime);

CREATE TABLE IF NOT EXISTS communication_files (
    communication_id    INTEGER NOT NULL,
    file_id             INTEGER NOT NULL,
    PRIMARY KEY (communication_id, file_id)
);

CREATE INDEX IF NOT EXISTS idx_muckrock_communication_files_file
    ON communication_files(file_id);

CREATE TABLE IF NOT EXISTS agencies (
    id                  INTEGER PRIMARY KEY,
    name                TEXT NOT NULL DEFAULT '',
    slug                TEXT NOT NULL DEFAULT '',
    status              TEXT NOT NULL DEFAULT '',
    jurisdiction_id     INTEGER,
    parent_id           INTEGER,
    appeal_agency_id    INTEGER,
    exempt              INTEGER NOT NULL DEFAULT 0,
    requires_proxy      INTEGER NOT NULL DEFAULT 0,
    types_json          TEXT NOT NULL DEFAULT '[]',
    indexed_at          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_muckrock_agencies_jurisdiction
    ON agencies(jurisdiction_id);

CREATE TABLE IF NOT EXISTS jurisdictions (
    id                  INTEGER PRIMARY KEY,
    name                TEXT NOT NULL DEFAULT '',
    slug                TEXT NOT NULL DEFAULT '',
    abbrev              TEXT NOT NULL DEFAULT '',
    level               TEXT NOT NULL DEFAULT '',
    parent_id           INTEGER,
    indexed_at          TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS crawl_state (
    collection          TEXT PRIMARY KEY,
    ordering            TEXT NOT NULL,
    next_page           INTEGER NOT NULL DEFAULT 1,
    total_count         INTEGER,
    rows_seen           INTEGER NOT NULL DEFAULT 0,
    completed           INTEGER NOT NULL DEFAULT 0,
    started_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL,
    completed_at        TEXT
);

CREATE VIRTUAL TABLE IF NOT EXISTS requests_fts USING fts5(
    title,
    requested_docs,
    tracking_id,
    content='requests',
    content_rowid='id',
    tokenize='porter unicode61'
);

CREATE TRIGGER IF NOT EXISTS muckrock_requests_ai AFTER INSERT ON requests BEGIN
    INSERT INTO requests_fts(rowid, title, requested_docs, tracking_id)
    VALUES (new.id, new.title, new.requested_docs, new.tracking_id);
END;
CREATE TRIGGER IF NOT EXISTS muckrock_requests_ad AFTER DELETE ON requests BEGIN
    INSERT INTO requests_fts(requests_fts, rowid, title, requested_docs, tracking_id)
    VALUES ('delete', old.id, old.title, old.requested_docs, old.tracking_id);
END;
CREATE TRIGGER IF NOT EXISTS muckrock_requests_au AFTER UPDATE ON requests BEGIN
    INSERT INTO requests_fts(requests_fts, rowid, title, requested_docs, tracking_id)
    VALUES ('delete', old.id, old.title, old.requested_docs, old.tracking_id);
    INSERT INTO requests_fts(rowid, title, requested_docs, tracking_id)
    VALUES (new.id, new.title, new.requested_docs, new.tracking_id);
END;

CREATE VIRTUAL TABLE IF NOT EXISTS communications_fts USING fts5(
    subject,
    communication_body,
    content='communications',
    content_rowid='id',
    tokenize='porter unicode61'
);

CREATE TRIGGER IF NOT EXISTS muckrock_communications_ai
AFTER INSERT ON communications BEGIN
    INSERT INTO communications_fts(rowid, subject, communication_body)
    VALUES (new.id, new.subject, new.communication_body);
END;
CREATE TRIGGER IF NOT EXISTS muckrock_communications_ad
AFTER DELETE ON communications BEGIN
    INSERT INTO communications_fts(
        communications_fts, rowid, subject, communication_body
    ) VALUES ('delete', old.id, old.subject, old.communication_body);
END;
CREATE TRIGGER IF NOT EXISTS muckrock_communications_au
AFTER UPDATE ON communications BEGIN
    INSERT INTO communications_fts(
        communications_fts, rowid, subject, communication_body
    ) VALUES ('delete', old.id, old.subject, old.communication_body);
    INSERT INTO communications_fts(rowid, subject, communication_body)
    VALUES (new.id, new.subject, new.communication_body);
END;

CREATE VIRTUAL TABLE IF NOT EXISTS files_fts USING fts5(
    title,
    source,
    description,
    url,
    doc_id,
    content='files',
    content_rowid='id',
    tokenize='porter unicode61'
);

CREATE TRIGGER IF NOT EXISTS muckrock_files_ai AFTER INSERT ON files BEGIN
    INSERT INTO files_fts(rowid, title, source, description, url, doc_id)
    VALUES (new.id, new.title, new.source, new.description, new.url, new.doc_id);
END;
CREATE TRIGGER IF NOT EXISTS muckrock_files_ad AFTER DELETE ON files BEGIN
    INSERT INTO files_fts(
        files_fts, rowid, title, source, description, url, doc_id
    ) VALUES (
        'delete', old.id, old.title, old.source, old.description, old.url,
        old.doc_id
    );
END;
CREATE TRIGGER IF NOT EXISTS muckrock_files_au AFTER UPDATE ON files BEGIN
    INSERT INTO files_fts(
        files_fts, rowid, title, source, description, url, doc_id
    ) VALUES (
        'delete', old.id, old.title, old.source, old.description, old.url,
        old.doc_id
    );
    INSERT INTO files_fts(rowid, title, source, description, url, doc_id)
    VALUES (new.id, new.title, new.source, new.description, new.url, new.doc_id);
END;

CREATE VIRTUAL TABLE IF NOT EXISTS agencies_fts USING fts5(
    name,
    content='agencies',
    content_rowid='id',
    tokenize='porter unicode61'
);

CREATE TRIGGER IF NOT EXISTS muckrock_agencies_ai AFTER INSERT ON agencies BEGIN
    INSERT INTO agencies_fts(rowid, name) VALUES (new.id, new.name);
END;
CREATE TRIGGER IF NOT EXISTS muckrock_agencies_ad AFTER DELETE ON agencies BEGIN
    INSERT INTO agencies_fts(agencies_fts, rowid, name)
    VALUES ('delete', old.id, old.name);
END;
CREATE TRIGGER IF NOT EXISTS muckrock_agencies_au AFTER UPDATE ON agencies BEGIN
    INSERT INTO agencies_fts(agencies_fts, rowid, name)
    VALUES ('delete', old.id, old.name);
    INSERT INTO agencies_fts(rowid, name) VALUES (new.id, new.name);
END;
"""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _get(obj, name, default=None):
    if isinstance(obj, dict):
        return obj.get(name, default)
    return getattr(obj, name, default)


def _object_id(value):
    if value is None or isinstance(value, (int, str)):
        return value
    return _get(value, "id", value)


def _text(value) -> str:
    return "" if value is None else str(value)


def _optional_text(value) -> str | None:
    return None if value is None else str(value)


def _json(value) -> str:
    return json.dumps(value if value is not None else [], default=str, sort_keys=True)


def connect_index(db_path: str | Path = DEFAULT_INDEX_DB) -> sqlite3.Connection:
    """Open an index database and ensure the schema exists."""
    path = Path(db_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(path)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA journal_mode=WAL")
    connection.execute("PRAGMA synchronous=NORMAL")
    connection.executescript(SCHEMA)
    columns = {
        row[1] for row in connection.execute("PRAGMA table_info(crawl_state)")
    }
    if "ordering" not in columns:
        connection.execute("ALTER TABLE crawl_state ADD COLUMN ordering TEXT")
    return connection


def _upsert_request(connection: sqlite3.Connection, obj, indexed_at: str) -> None:
    connection.execute(
        """
        INSERT INTO requests(
            id, title, requested_docs, slug, status, agency_id, user_id,
            embargo_status, datetime_submitted, datetime_updated, datetime_done,
            tracking_id, price, tags_json, indexed_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
            title=excluded.title,
            requested_docs=excluded.requested_docs,
            slug=excluded.slug,
            status=excluded.status,
            agency_id=excluded.agency_id,
            user_id=excluded.user_id,
            embargo_status=excluded.embargo_status,
            datetime_submitted=excluded.datetime_submitted,
            datetime_updated=excluded.datetime_updated,
            datetime_done=excluded.datetime_done,
            tracking_id=excluded.tracking_id,
            price=excluded.price,
            tags_json=excluded.tags_json,
            indexed_at=excluded.indexed_at
        """,
        (
            _get(obj, "id"),
            _text(_get(obj, "title")),
            _text(_get(obj, "requested_docs")),
            _text(_get(obj, "slug")),
            _text(_get(obj, "status")),
            _object_id(_get(obj, "agency")),
            _object_id(_get(obj, "user")),
            _text(_get(obj, "embargo_status")),
            _text(_get(obj, "datetime_submitted")),
            _text(_get(obj, "datetime_updated")),
            _text(_get(obj, "datetime_done")),
            _text(_get(obj, "tracking_id")),
            _text(_get(obj, "price")),
            _json(_get(obj, "tags")),
            indexed_at,
        ),
    )


def _upsert_communication(
    connection: sqlite3.Connection, obj, indexed_at: str
) -> None:
    communication_id = _get(obj, "id")
    connection.execute(
        """
        INSERT INTO communications(
            id, request_id, from_user_id, to_user_id, subject, datetime,
            response, autogenerated, communication_body, status, indexed_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
            request_id=excluded.request_id,
            from_user_id=excluded.from_user_id,
            to_user_id=excluded.to_user_id,
            subject=excluded.subject,
            datetime=excluded.datetime,
            response=excluded.response,
            autogenerated=excluded.autogenerated,
            communication_body=excluded.communication_body,
            status=excluded.status,
            indexed_at=excluded.indexed_at
        """,
        (
            communication_id,
            _object_id(_get(obj, "foia")),
            _object_id(_get(obj, "from_user")),
            _object_id(_get(obj, "to_user")),
            _text(_get(obj, "subject")),
            _text(_get(obj, "datetime")),
            int(bool(_get(obj, "response", False))),
            int(bool(_get(obj, "autogenerated", False))),
            _text(_get(obj, "communication")),
            _text(_get(obj, "status")),
            indexed_at,
        ),
    )
    connection.execute(
        "DELETE FROM communication_files WHERE communication_id = ?",
        (communication_id,),
    )
    for file_ref in _get(obj, "files", []) or []:
        file_id = _object_id(file_ref)
        if file_id is not None:
            connection.execute(
                """
                INSERT OR IGNORE INTO communication_files(communication_id, file_id)
                VALUES (?, ?)
                """,
                (communication_id, file_id),
            )


def _upsert_file(connection: sqlite3.Connection, obj, indexed_at: str) -> None:
    connection.execute(
        """
        INSERT INTO files(
            id, url, datetime, title, source, description, doc_id, pages,
            indexed_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
            url=excluded.url,
            datetime=excluded.datetime,
            title=excluded.title,
            source=excluded.source,
            description=excluded.description,
            doc_id=excluded.doc_id,
            pages=excluded.pages,
            indexed_at=excluded.indexed_at
        """,
        (
            _get(obj, "id"),
            _text(_get(obj, "ffile")),
            _text(_get(obj, "datetime")),
            _text(_get(obj, "title")),
            _text(_get(obj, "source")),
            _text(_get(obj, "description")),
            _optional_text(_get(obj, "doc_id")),
            _get(obj, "pages"),
            indexed_at,
        ),
    )


def _upsert_agency(connection: sqlite3.Connection, obj, indexed_at: str) -> None:
    connection.execute(
        """
        INSERT INTO agencies(
            id, name, slug, status, jurisdiction_id, parent_id,
            appeal_agency_id, exempt, requires_proxy, types_json, indexed_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
            name=excluded.name,
            slug=excluded.slug,
            status=excluded.status,
            jurisdiction_id=excluded.jurisdiction_id,
            parent_id=excluded.parent_id,
            appeal_agency_id=excluded.appeal_agency_id,
            exempt=excluded.exempt,
            requires_proxy=excluded.requires_proxy,
            types_json=excluded.types_json,
            indexed_at=excluded.indexed_at
        """,
        (
            _get(obj, "id"),
            _text(_get(obj, "name")),
            _text(_get(obj, "slug")),
            _text(_get(obj, "status")),
            _object_id(_get(obj, "jurisdiction")),
            _object_id(_get(obj, "parent")),
            _object_id(_get(obj, "appeal_agency")),
            int(bool(_get(obj, "exempt", False))),
            int(bool(_get(obj, "requires_proxy", False))),
            _json(_get(obj, "types")),
            indexed_at,
        ),
    )


def _upsert_jurisdiction(
    connection: sqlite3.Connection, obj, indexed_at: str
) -> None:
    connection.execute(
        """
        INSERT INTO jurisdictions(
            id, name, slug, abbrev, level, parent_id, indexed_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
            name=excluded.name,
            slug=excluded.slug,
            abbrev=excluded.abbrev,
            level=excluded.level,
            parent_id=excluded.parent_id,
            indexed_at=excluded.indexed_at
        """,
        (
            _get(obj, "id"),
            _text(_get(obj, "name")),
            _text(_get(obj, "slug")),
            _text(_get(obj, "abbrev")),
            _text(_get(obj, "level")),
            _object_id(_get(obj, "parent")),
            indexed_at,
        ),
    )


UPSERT_HANDLERS = {
    "requests": _upsert_request,
    "communications": _upsert_communication,
    "files": _upsert_file,
    "agencies": _upsert_agency,
    "jurisdictions": _upsert_jurisdiction,
}


def ingest_page(
    connection: sqlite3.Connection, collection: str, rows: Iterable
) -> int:
    """Upsert one API page and return its row count."""
    handler = UPSERT_HANDLERS[collection]
    indexed_at = _now()
    count = 0
    for row in rows:
        handler(connection, row, indexed_at)
        count += 1
    return count


def _crawl_state(connection: sqlite3.Connection, collection: str):
    return connection.execute(
        "SELECT * FROM crawl_state WHERE collection = ?", (collection,)
    ).fetchone()


def _set_crawl_state(
    connection: sqlite3.Connection,
    *,
    collection: str,
    ordering: str,
    next_page: int,
    total_count: int | None,
    rows_seen: int,
    completed: bool,
    started_at: str,
) -> None:
    now = _now()
    connection.execute(
        """
        INSERT INTO crawl_state(
            collection, ordering, next_page, total_count, rows_seen, completed,
            started_at, updated_at, completed_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(collection) DO UPDATE SET
            ordering=excluded.ordering,
            next_page=excluded.next_page,
            total_count=excluded.total_count,
            rows_seen=excluded.rows_seen,
            completed=excluded.completed,
            started_at=excluded.started_at,
            updated_at=excluded.updated_at,
            completed_at=excluded.completed_at
        """,
        (
            collection,
            ordering,
            next_page,
            total_count,
            rows_seen,
            int(completed),
            started_at,
            now,
            now if completed else None,
        ),
    )


def crawl_index(
    client,
    *,
    db_path: str | Path = DEFAULT_INDEX_DB,
    collections: Iterable[str] = COLLECTIONS,
    max_pages: int = 0,
    delay: float = 1.0,
    restart: bool = False,
    progress: Callable[[str, int, int, int | None], None] | None = None,
) -> dict:
    """Crawl selected API collections into a resumable local index.

    Collections are interleaved so each endpoint remains near the official
    wrapper's conservative per-endpoint rate while aggregate requests remain at
    or below the API's documented one-request-per-second average.
    """
    selected = list(dict.fromkeys(collections))
    invalid = sorted(set(selected) - set(COLLECTIONS))
    if invalid:
        raise ValueError(f"Unknown MuckRock collections: {', '.join(invalid)}")
    if max_pages < 0:
        raise ValueError("max_pages cannot be negative")
    if delay < 0:
        raise ValueError("delay cannot be negative")

    connection = connect_index(db_path)
    started = _now()
    states: list[dict] = []
    summaries: dict[str, dict] = {}
    try:
        if restart:
            placeholders = ",".join("?" for _ in selected)
            connection.execute(
                f"DELETE FROM crawl_state WHERE collection IN ({placeholders})",
                selected,
            )
            connection.commit()

        for collection in selected:
            saved = _crawl_state(connection, collection)
            ordering = COLLECTION_ORDERING[collection]
            saved_ordering = saved["ordering"] if saved else None
            if saved and saved_ordering != ordering:
                raise ValueError(
                    f"Saved {collection} cursor uses ordering {saved_ordering!r}; "
                    f"current ordering is {ordering!r}. Re-run with --restart."
                )
            if saved and saved["completed"]:
                summaries[collection] = {
                    "pages": 0,
                    "rows": 0,
                    "total": saved["total_count"],
                    "completed": True,
                    "next_page": saved["next_page"],
                    "skipped": "already complete; use --restart to refresh",
                }
                continue

            next_page = int(saved["next_page"]) if saved else 1
            rows_seen = int(saved["rows_seen"]) if saved else 0
            crawl_started = saved["started_at"] if saved else started
            state = {
                "collection": collection,
                "ordering": ordering,
                "page": next_page,
                "run_pages": 0,
                "run_rows": 0,
                "rows_seen": rows_seen,
                "total": saved["total_count"] if saved else None,
                "started_at": crawl_started,
            }
            states.append(state)
            summaries[collection] = {
                "pages": 0,
                "rows": 0,
                "total": state["total"],
                "completed": False,
                "next_page": next_page,
            }

        last_request_started: float | None = None
        while states:
            for state in list(states):
                if max_pages and state["run_pages"] >= max_pages:
                    states.remove(state)
                    continue

                if last_request_started is not None:
                    remaining = delay - (time.monotonic() - last_request_started)
                    if remaining > 0:
                        time.sleep(remaining)

                collection = state["collection"]
                page = state["page"]
                manager = getattr(client, collection)
                last_request_started = time.monotonic()
                api_results = manager.list(
                    page=page,
                    page_size=PAGE_SIZE,
                    ordering=state["ordering"],
                )
                page_rows = list(api_results.results)
                total = getattr(api_results, "count", None)
                if total is not None:
                    total = int(total)

                with connection:
                    row_count = ingest_page(connection, collection, page_rows)
                    state["run_pages"] += 1
                    state["run_rows"] += row_count
                    state["rows_seen"] += row_count
                    state["total"] = total
                    completed = not bool(getattr(api_results, "next_url", None))
                    next_page = page + 1
                    _set_crawl_state(
                        connection,
                        collection=collection,
                        ordering=state["ordering"],
                        next_page=next_page,
                        total_count=total,
                        rows_seen=state["rows_seen"],
                        completed=completed,
                        started_at=state["started_at"],
                    )

                if progress:
                    progress(collection, page, row_count, total)

                summary = summaries[collection]
                summary.update(
                    {
                        "pages": state["run_pages"],
                        "rows": state["run_rows"],
                        "total": total,
                        "completed": completed,
                        "next_page": next_page,
                    }
                )
                if completed:
                    states.remove(state)
                else:
                    state["page"] = next_page

        return {
            "db": str(Path(db_path)),
            "page_size": PAGE_SIZE,
            "collections": summaries,
            "pages_fetched": sum(item["pages"] for item in summaries.values()),
            "rows_upserted": sum(item["rows"] for item in summaries.values()),
            "started_at": started,
            "finished_at": _now(),
        }
    finally:
        connection.close()


def _fts_query(query: str | None) -> str | None:
    if not query:
        return None
    tokens = re.findall(r"[^\W_]+(?:[-./@][^\W_]+)*", query, flags=re.UNICODE)
    if not tokens:
        return None
    return " AND ".join(f'"{token.replace(chr(34), chr(34) * 2)}"' for token in tokens)


def _excerpt(text: str, query: str | None, width: int = 500) -> str:
    collapsed = re.sub(r"\s+", " ", text or "").strip()
    if len(collapsed) <= width:
        return collapsed
    start = 0
    if query:
        terms = re.findall(r"[^\W_]+", query, flags=re.UNICODE)
        lowered = collapsed.lower()
        positions = [lowered.find(term.lower()) for term in terms]
        positions = [position for position in positions if position >= 0]
        if positions:
            start = max(0, min(positions) - width // 3)
    excerpt = collapsed[start : start + width]
    return ("…" if start else "") + excerpt + (
        "…" if start + width < len(collapsed) else ""
    )


def search_index(
    *,
    db_path: str | Path = DEFAULT_INDEX_DB,
    query: str | None = None,
    without_documentcloud: bool = False,
    response_only: bool = False,
    agency_id: int | None = None,
    limit: int = 100,
) -> list[dict]:
    """Search indexed requests/correspondence/file metadata, returning files."""
    path = Path(db_path)
    if not path.exists():
        raise FileNotFoundError(f"MuckRock index does not exist: {path}")
    if limit < 1:
        raise ValueError("limit must be at least 1")

    connection = connect_index(path)
    try:
        fts_query = _fts_query(query)
        params: dict[str, object] = {"limit": limit}
        if fts_query:
            params["fts_query"] = fts_query
            matched_files = """
                SELECT cf.file_id
                FROM requests_fts
                JOIN communications c ON c.request_id = requests_fts.rowid
                JOIN communication_files cf ON cf.communication_id = c.id
                WHERE requests_fts MATCH :fts_query
                UNION
                SELECT cf.file_id
                FROM communications_fts
                JOIN communication_files cf
                    ON cf.communication_id = communications_fts.rowid
                WHERE communications_fts MATCH :fts_query
                UNION
                SELECT rowid AS file_id
                FROM files_fts
                WHERE files_fts MATCH :fts_query
            """
        else:
            matched_files = "SELECT id AS file_id FROM files"

        filters = []
        if without_documentcloud:
            filters.append("NULLIF(TRIM(f.doc_id), '') IS NULL")
        if response_only:
            filters.append("c.response = 1")
        if agency_id is not None:
            filters.append("r.agency_id = :agency_id")
            params["agency_id"] = agency_id
        where = "WHERE " + " AND ".join(filters) if filters else ""

        rows = connection.execute(
            f"""
            WITH matched_files(file_id) AS ({matched_files})
            SELECT DISTINCT
                f.id AS file_id,
                f.title AS file_title,
                f.url AS file_url,
                f.pages,
                f.datetime AS file_datetime,
                f.source AS file_source,
                f.description AS file_description,
                f.doc_id,
                CASE WHEN NULLIF(TRIM(f.doc_id), '') IS NULL
                     THEN 1 ELSE 0 END AS documentcloud_unlinked,
                c.id AS communication_id,
                c.datetime AS communication_datetime,
                c.subject AS communication_subject,
                c.communication_body,
                c.response,
                r.id AS request_id,
                r.title AS request_title,
                r.requested_docs,
                r.slug AS request_slug,
                r.status AS request_status,
                r.agency_id,
                a.name AS agency_name
            FROM matched_files mf
            JOIN files f ON f.id = mf.file_id
            JOIN communication_files cf ON cf.file_id = f.id
            JOIN communications c ON c.id = cf.communication_id
            LEFT JOIN requests r ON r.id = c.request_id
            LEFT JOIN agencies a ON a.id = r.agency_id
            {where}
            ORDER BY
                COALESCE(NULLIF(f.datetime, ''), NULLIF(c.datetime, ''),
                         NULLIF(r.datetime_updated, '')) DESC,
                f.id DESC
            LIMIT :limit
            """,
            params,
        ).fetchall()

        results = []
        for row in rows:
            result = dict(row)
            result["documentcloud_unlinked"] = bool(
                result["documentcloud_unlinked"]
            )
            result["response"] = bool(result["response"])
            result["communication_excerpt"] = _excerpt(
                result.pop("communication_body"), query
            )
            result["requested_docs_excerpt"] = _excerpt(
                result.pop("requested_docs"), query
            )
            request_id = result.get("request_id")
            result["request_url"] = (
                f"https://www.muckrock.com/foi/request/{request_id}/"
                if request_id is not None
                else ""
            )
            results.append(result)
        return results
    finally:
        connection.close()


def index_stats(db_path: str | Path = DEFAULT_INDEX_DB) -> dict:
    """Return corpus counts, DocumentCloud linkage counts, and crawl cursors."""
    path = Path(db_path)
    if not path.exists():
        raise FileNotFoundError(f"MuckRock index does not exist: {path}")
    connection = connect_index(path)
    try:
        counts = {
            table: connection.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            for table in (
                "requests",
                "communications",
                "files",
                "communication_files",
                "agencies",
                "jurisdictions",
            )
        }
        linkage = dict(
            connection.execute(
                """
                SELECT
                    SUM(CASE WHEN NULLIF(TRIM(doc_id), '') IS NULL
                             THEN 1 ELSE 0 END) AS documentcloud_unlinked,
                    SUM(CASE WHEN NULLIF(TRIM(doc_id), '') IS NOT NULL
                             THEN 1 ELSE 0 END) AS documentcloud_linked
                FROM files
                """
            ).fetchone()
        )
        linkage["unlinked_response_files"] = connection.execute(
            """
            SELECT COUNT(DISTINCT f.id)
            FROM files f
            JOIN communication_files cf ON cf.file_id = f.id
            JOIN communications c ON c.id = cf.communication_id
            WHERE NULLIF(TRIM(f.doc_id), '') IS NULL AND c.response = 1
            """
        ).fetchone()[0]
        linkage["file_records_without_communication"] = connection.execute(
            """
            SELECT COUNT(*) FROM files f
            WHERE NOT EXISTS (
                SELECT 1 FROM communication_files cf WHERE cf.file_id = f.id
            )
            """
        ).fetchone()[0]
        linkage["unresolved_file_references"] = connection.execute(
            """
            SELECT COUNT(*) FROM communication_files cf
            LEFT JOIN files f ON f.id = cf.file_id
            WHERE f.id IS NULL
            """
        ).fetchone()[0]
        crawl = [
            dict(row)
            for row in connection.execute(
                "SELECT * FROM crawl_state ORDER BY collection"
            ).fetchall()
        ]
        for row in crawl:
            row["completed"] = bool(row["completed"])
        return {
            "db": str(path),
            "counts": counts,
            "documentcloud_linkage": linkage,
            "crawl_state": crawl,
        }
    finally:
        connection.close()
