#!/usr/bin/env python3
"""Peru SEACE (Sistema Electrónico de Contrataciones del Estado) query tool.

Searches the public procurement record published by OECE/OSCE under the
CONOSCE open-data initiative. The interactive search portal at
prodapp2.seace.gob.pe is a JSF/PrimeFaces app that requires a browser
session, but OSCE publishes the same underlying data as yearly XLSX dumps
under conosce.osce.gob.pe — that is the substrate this tool queries.

Endpoint discovery (probed 2026-04-27):
    The CONOSCE open-data index pages live at:
        https://bi.seace.gob.pe/pentaho/api/repos/:public:portal:datosabiertos*.html/content
    Each one links to tinyurl shortcuts that resolve to year/dataset XLSX
    files at:
        https://conosce.osce.gob.pe/buscador/assets/67ae6c4a/reportes/{kind}/{YYYY}/CONOSCE_{KIND}{YYYY}_0.xlsx
    where:
        kind in {"convocatorias","adjudicaciones"}
        KIND in {"CONVOCATORIAS", "CONVOCATORIAS_CD" (contratación directa),
                 "CONVOCATORIAS_SIE" (subasta inversa electrónica),
                 "ADJUDICACIONES", "ADJUDICACIONES_CD", "ADJUDICACIONES_SIE"}
    Also available:
        Diccionario de datos:
            https://conosce.osce.gob.pe/buscador/assets/67ae6c4a/reportes/Diccionario.xlsx
        Listado de Entidades Contratantes (current snapshot, CSV):
            https://osce-gob-pe.atlassian.net/wiki/download/attachments/
            106889265/entidades_contratantes.csv?version=33&...&api=v2

The portal SPA at prod2.seace.gob.pe blocks programmatic access (HTTP 403);
the OCDS/Open Contracting portal at contratacionesabiertas.osce.gob.pe was
NXDOMAIN from this network on 2026-04-27. The CONOSCE bulk dumps are the
working substrate for offline / batch search and are the canonical OECE-
published open-data version of the same SEACE records.

NOTE on the F-16 procurement: declared "secreto militar" via DS Nº 001-2026-DE
(El Peruano 2026-01-12), so the prime contract is NOT expected to appear in
SEACE/CONOSCE. Use this tool for related procurement (training, sustainment,
SEMAN PERU SAC contracts, FAP infrastructure, vendor-side Peruvian work).

Usage:
    uv run python tools/query_seace.py search \\
        --entity "Fuerza Aérea del Perú" \\
        --year 2025 --output fap-2025.json

    uv run python tools/query_seace.py search \\
        --keyword "F-16" --year 2024 --year 2025 --year 2026 \\
        --output f16.json

    uv run python tools/query_seace.py search \\
        --vendor SEMAN --output seman-all.json

    # The "contract" subcommand returns the row matching a specific
    # convocation id (CODIGOCONVOCATORIA) or contract nomenclature.
    uv run python tools/query_seace.py contract LP-SM-1-2025-FAP/1 \\
        --output contract.json

The first time a year/dataset is queried the XLSX is downloaded to
$SEACE_CACHE_DIR (default: ./datasets/seace/cache/). Subsequent runs reuse
the cached file unless --refresh is passed.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
import unicodedata
from pathlib import Path
from typing import Iterable, Iterator
from urllib.parse import urlparse

import requests
from openpyxl import load_workbook

# ---------------------------------------------------------------- constants ----

USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0 Safari/537.36"
)

# Real (post-tinyurl) URL pattern. The "67ae6c4a" path segment is a Yii2
# build-asset hash that is regenerated by the upstream app; if downloads
# break in the future, refetch the index at:
#   https://bi.seace.gob.pe/pentaho/api/repos/:public:portal:datosabiertosconvocatorias.html/content?userid=public&password=key
# and re-parse the tinyurl redirects.
ASSETS_BASE = "https://conosce.osce.gob.pe/buscador/assets/67ae6c4a/reportes"

DATASETS = {
    # name -> (subdir, file-template fragment)
    "convocatorias":     ("convocatorias",  "CONOSCE_CONVOCATORIAS{YYYY}_0.xlsx"),
    "convocatorias_cd":  ("convocatorias",  "CONOSCE_CONVOCATORIAS_CD{YYYY}_0.xlsx"),
    "convocatorias_sie": ("convocatorias",  "CONOSCE_CONVOCATORIAS_SIE{YYYY}_0.xlsx"),
    "adjudicaciones":    ("adjudicaciones", "CONOSCE_ADJUDICACIONES{YYYY}_0.xlsx"),
    "adjudicaciones_cd": ("adjudicaciones", "CONOSCE_ADJUDICACIONES_CD{YYYY}_0.xlsx"),
    "adjudicaciones_sie":("adjudicaciones", "CONOSCE_ADJUDICACIONES_SIE{YYYY}_0.xlsx"),
}

DICCIONARIO_URL = f"{ASSETS_BASE}/Diccionario.xlsx"
ENTIDADES_CSV_URL = (
    "https://osce-gob-pe.atlassian.net/wiki/download/attachments/"
    "106889265/entidades_contratantes.csv"
    "?version=33&modificationDate=1740831792989&cacheVersion=1&api=v2"
)

DEFAULT_CACHE = Path(os.environ.get("SEACE_CACHE_DIR", "datasets/seace/cache"))


# ---------------------------------------------------------------- utilities ----

def _norm(s: object) -> str:
    """Lowercase, strip accents, collapse whitespace — for fuzzy matching."""
    if s is None:
        return ""
    txt = str(s)
    txt = unicodedata.normalize("NFKD", txt)
    txt = "".join(ch for ch in txt if not unicodedata.combining(ch))
    return re.sub(r"\s+", " ", txt).strip().lower()


def _session() -> requests.Session:
    s = requests.Session()
    s.headers.update({
        "User-Agent": USER_AGENT,
        "Accept": "application/octet-stream, */*",
    })
    return s


def _dataset_url(dataset: str, year: int) -> str:
    if dataset not in DATASETS:
        raise ValueError(f"Unknown dataset {dataset!r}; valid: {sorted(DATASETS)}")
    subdir, tmpl = DATASETS[dataset]
    fname = tmpl.format(YYYY=year)
    return f"{ASSETS_BASE}/{subdir}/{year}/{fname}"


def _cache_path(cache_dir: Path, dataset: str, year: int) -> Path:
    cache_dir.mkdir(parents=True, exist_ok=True)
    _, tmpl = DATASETS[dataset]
    return cache_dir / tmpl.format(YYYY=year)


def fetch_dataset(dataset: str, year: int, cache_dir: Path = DEFAULT_CACHE,
                  refresh: bool = False, timeout: int = 180) -> Path:
    """Download (or reuse cached) yearly XLSX dataset and return its path."""
    target = _cache_path(cache_dir, dataset, year)
    if target.exists() and not refresh:
        return target
    url = _dataset_url(dataset, year)
    sess = _session()
    print(f"  downloading {dataset} {year} ...", file=sys.stderr)
    resp = sess.get(url, timeout=timeout, stream=True)
    if resp.status_code == 404:
        raise FileNotFoundError(f"Dataset not yet published: {url}")
    resp.raise_for_status()
    tmp = target.with_suffix(".part")
    with open(tmp, "wb") as fh:
        for chunk in resp.iter_content(chunk_size=1 << 15):
            if chunk:
                fh.write(chunk)
    tmp.rename(target)
    return target


def iter_rows(xlsx_path: Path) -> Iterator[dict]:
    """Yield each row of the dataset as a dict keyed by the column header.

    Uses read_only iter — the convocatorias 2025 file is ~18 MB and contains
    >70k rows; a streaming iterator avoids pinning the whole sheet in memory.
    """
    wb = load_workbook(filename=xlsx_path, read_only=True, data_only=True)
    ws = wb.active
    rows = ws.iter_rows(values_only=True)
    try:
        headers = [str(h).strip() if h is not None else "" for h in next(rows)]
    except StopIteration:
        wb.close()
        return
    for raw in rows:
        if raw is None:
            continue
        if all(v is None or str(v).strip() == "" for v in raw):
            continue
        # Pad/truncate to header length so dict keys line up
        vals = list(raw) + [None] * (len(headers) - len(raw))
        yield {headers[i] or f"col_{i}": vals[i] for i in range(len(headers))}
    wb.close()


# ---------------------------------------------------------------- search ----

def _row_matches(row: dict, *,
                 entity_terms: list[str],
                 vendor_terms: list[str],
                 keyword_terms: list[str],
                 process_type: str | None) -> bool:
    """Return True if all configured filters match the row.

    The CONOSCE schema varies across datasets but the relevant columns
    consistently include:
        ENTIDAD_CONVOCANTE / N_ENTIDAD_CONVOCANTE / ENTIDADCONVOCANTE
        OBJETOCONTRACTUAL / DESCRIPCION_OBJETO / DESCRIPCION_DEL_PROCESO
            / NOMBREOBJETO / NOMENCLATURA
        TIPOPROCESO / TIPO_PROCESO / TIPOSELECCION / SIGLAPROCESO
        RUC_PROVEEDOR / NOMBRE_PROVEEDOR / DESPROVEEDOR / NOMBREPOSTOR
            / NOMBREGANADOR / RAZONSOCIAL_PROVEEDOR
    Rather than hard-coding column names per dataset version, we match
    against the union of all values in the row, scoped by intent (entity vs
    vendor vs free keyword), to be resilient to schema drift.
    """
    if not (entity_terms or vendor_terms or keyword_terms or process_type):
        return True

    keys = {k.upper(): k for k in row.keys()}

    def _values_for(prefix_set: tuple[str, ...]) -> str:
        bits: list[str] = []
        for upper, original in keys.items():
            if any(p in upper for p in prefix_set):
                v = row.get(original)
                if v not in (None, ""):
                    bits.append(_norm(v))
        return " | ".join(bits)

    if entity_terms:
        hay = _values_for(("ENTIDAD",)) or _values_for(("CONVOCANTE",))
        if not all(t in hay for t in entity_terms):
            return False

    if vendor_terms:
        hay = _values_for((
            "PROVEEDOR", "POSTOR", "GANADOR", "RAZON_SOCIAL", "RAZONSOCIAL"
        ))
        if not all(t in hay for t in vendor_terms):
            return False

    if process_type:
        hay = _values_for(("TIPO", "SIGLAPROCESO", "MODALIDAD"))
        if _norm(process_type) not in hay:
            return False

    if keyword_terms:
        # full-row search for free-text keywords (last so we short-circuit other filters first)
        full = " | ".join(_norm(v) for v in row.values() if v not in (None, ""))
        if not all(t in full for t in keyword_terms):
            return False

    return True


def cmd_search(args: argparse.Namespace) -> None:
    cache_dir = Path(args.cache_dir or DEFAULT_CACHE)

    years = args.year or [2024, 2025, 2026]
    datasets = args.dataset or ["convocatorias", "adjudicaciones"]

    entity_terms = [_norm(t) for t in (args.entity or [])]
    vendor_terms = [_norm(t) for t in (args.vendor or [])]
    keyword_terms = [_norm(t) for t in (args.keyword or [])]

    matches: list[dict] = []
    counts_by_source: dict[str, int] = {}
    fetch_errors: list[dict] = []

    for year in years:
        for dataset in datasets:
            try:
                path = fetch_dataset(dataset, year, cache_dir=cache_dir,
                                     refresh=args.refresh)
            except FileNotFoundError as e:
                fetch_errors.append({"dataset": dataset, "year": year,
                                     "error": str(e)})
                continue
            except requests.RequestException as e:
                fetch_errors.append({"dataset": dataset, "year": year,
                                     "error": f"http: {e}"})
                continue

            n_match = 0
            for row in iter_rows(path):
                if _row_matches(row,
                                entity_terms=entity_terms,
                                vendor_terms=vendor_terms,
                                keyword_terms=keyword_terms,
                                process_type=args.process_type):
                    enriched = {
                        "_dataset": dataset,
                        "_year": year,
                        "_source_url": _dataset_url(dataset, year),
                        **{k: v for k, v in row.items() if v not in (None, "")},
                    }
                    matches.append(enriched)
                    n_match += 1
                    if args.limit and len(matches) >= args.limit:
                        break
            counts_by_source[f"{dataset}-{year}"] = n_match
            if args.limit and len(matches) >= args.limit:
                break
        if args.limit and len(matches) >= args.limit:
            break

    out = {
        "tool": "query_seace.py",
        "command": "search",
        "filters": {
            "entity": args.entity, "vendor": args.vendor,
            "keyword": args.keyword, "process_type": args.process_type,
            "years": years, "datasets": datasets,
            "limit": args.limit,
        },
        "match_counts_by_source": counts_by_source,
        "fetch_errors": fetch_errors,
        "total_matches": len(matches),
        "matches": matches,
    }
    Path(args.output).write_text(json.dumps(out, ensure_ascii=False, indent=2,
                                            default=str))
    print(f"Wrote {len(matches)} matches across "
          f"{len(years)*len(datasets)} datasets to {args.output}",
          file=sys.stderr)


# ---------------------------------------------------------------- contract ----

def cmd_contract(args: argparse.Namespace) -> None:
    """Look up a single procedure by id (CODIGOCONVOCATORIA or NOMENCLATURA)."""
    cache_dir = Path(args.cache_dir or DEFAULT_CACHE)
    needle = _norm(args.id)

    years = args.year or list(range(2024, 2027))
    datasets = list(DATASETS.keys())

    found: list[dict] = []
    for year in years:
        for dataset in datasets:
            try:
                path = fetch_dataset(dataset, year, cache_dir=cache_dir,
                                     refresh=args.refresh)
            except (FileNotFoundError, requests.RequestException):
                continue
            for row in iter_rows(path):
                # Look in any column whose header mentions CODIGO/NOMENCLATURA/ID
                hay_bits: list[str] = []
                for k, v in row.items():
                    if v in (None, ""):
                        continue
                    ku = k.upper()
                    if any(t in ku for t in
                           ("CODIGO", "NOMENCLATURA", "ID", "CONVOCATORIA",
                            "EXPEDIENTE", "PROCESO", "NUMEROCONTRATO")):
                        hay_bits.append(_norm(v))
                if needle and any(needle in h for h in hay_bits):
                    found.append({
                        "_dataset": dataset, "_year": year,
                        "_source_url": _dataset_url(dataset, year),
                        **{k: v for k, v in row.items() if v not in (None, "")},
                    })

    out = {
        "tool": "query_seace.py", "command": "contract",
        "id": args.id, "matches": found, "count": len(found),
    }
    Path(args.output).write_text(json.dumps(out, ensure_ascii=False, indent=2,
                                            default=str))
    print(f"Wrote {len(found)} matches for id={args.id!r} to {args.output}",
          file=sys.stderr)


# ---------------------------------------------------------------- entities ----

def cmd_entities(args: argparse.Namespace) -> None:
    """Download the entidades-contratantes lookup CSV (issued by OSCE)."""
    sess = _session()
    resp = sess.get(ENTIDADES_CSV_URL, timeout=120)
    resp.raise_for_status()
    target = Path(args.output)
    target.write_bytes(resp.content)
    print(f"Wrote entidades CSV ({len(resp.content)} bytes) to {target}",
          file=sys.stderr)


# ---------------------------------------------------------------- main ----

def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("search", help="Filter CONOSCE yearly dumps")
    s.add_argument("--entity", action="append",
                   help="Entity-name term (multiple = AND); fuzzy match")
    s.add_argument("--vendor", action="append",
                   help="Vendor-name / RUC term (multiple = AND)")
    s.add_argument("--keyword", action="append",
                   help="Free-text term anywhere on the row")
    s.add_argument("--year", type=int, action="append",
                   help="Year(s) to query; default 2024-2026")
    s.add_argument("--dataset", action="append",
                   choices=sorted(DATASETS.keys()),
                   help="Dataset(s); default convocatorias+adjudicaciones")
    s.add_argument("--process-type",
                   help="TIPO_PROCESO filter (e.g., 'CONTRATACION DIRECTA',"
                        " 'CONCURSO PUBLICO', 'LICITACION PUBLICA')")
    s.add_argument("--limit", type=int,
                   help="Stop after N matches (useful for fanout searches)")
    s.add_argument("--cache-dir",
                   help=f"Override XLSX cache dir (default {DEFAULT_CACHE})")
    s.add_argument("--refresh", action="store_true",
                   help="Force re-download of cached XLSX files")
    s.add_argument("--output", required=True, help="JSON output path")
    s.set_defaults(func=cmd_search)

    c = sub.add_parser("contract", help="Look up a single procedure by id")
    c.add_argument("id", help="CODIGOCONVOCATORIA, nomenclatura, or expediente id")
    c.add_argument("--year", type=int, action="append")
    c.add_argument("--cache-dir")
    c.add_argument("--refresh", action="store_true")
    c.add_argument("--output", required=True)
    c.set_defaults(func=cmd_contract)

    e = sub.add_parser("entities",
                       help="Download Listado de Entidades Contratantes (CSV)")
    e.add_argument("--output", required=True, help="CSV output path")
    e.set_defaults(func=cmd_entities)

    args = p.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
